var arr = new Array("First", "Second", "Third");
var str = arr.join();
console.log("str : " + str);
var str = arr.join(", ");
console.log("str : " + str);
var str = arr.join(" + ");
console.log("str : " + str);
var numbers = [1, 4, 9];
var roots = numbers.map(Math.sqrt);
console.log("roots is : " + roots);
